name: ImigraWeb Backend

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    lint_testing:
      name: Lint & Testing
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: astral-sh/setup-uv@v6
          with:
            version: "latest"
        - run: |
            uv sync --all-groups
            uv run ruff check backend
            uv run pytest -v
    build:
      name: Build
      needs: lint_testing
      runs-on: ubuntu-latest
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            registry: registry.digitalocean.com
            username: danilo.paes@pm.me
            password: dop_v1_9d3521d12e439c04cadabc163565e724c956c6060dfaa56ce78da191b932cdc5
        - run: |
            docker build -t registry.digitalocean.com/imigraweb:latest .
            docker push registry.digitalocean.com/imigraweb:latest
