name: ImigraWeb Backend

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: astral-sh/setup-uv@v6
            with:
              version: "latest"
          - run: |
              uv sync --all-groups
              uv run ruff check backend
